### PR TITLE
Add an audio track to SolLevante mov example

### PR DESCRIPTION
**Pull request by ThomasWilshaw**
After some discussion on the OTIO Slack channel I thought it might be useful to add another example file here that explicitly contained an audio track. I've not used the Python API much before so let me know if there are any issues with the code. Below is a screenshot of the timeline in `otioview`.

image

### CODE REVIEW

**Comment by darbyjohnston** [comment]
Hi! Thanks, this will be great to have an audio example. Also thanks for adding the script. I'll merge this and add a link to the .otio file in README.md.

I just realized I should probably add a license for this content, maybe the same license as the Netflix Open Content, or maybe the new ASWF asset license?

**Comment by darbyjohnston** [comment]
Actually I wonder after merging this fs we should replace the original .otio file with the audio version? Is it worthwhile to have both a non-audio and audio version?

**Comment by ThomasWilshaw** [comment]
No problem, it was a pretty quick job. I can see your point, I can't really think of a use case where not having audio would be beneficial. 

I must confess I don't know anything about licenses, is there someone at the ASWF that could advise do you think? From my point of view, feel free to do whatever is best with the files I've contributed.

**Comment by darbyjohnston** [comment]
OK cool, I'll remove the non-audio version.

I just reached out to the ASWF slack channel to see if anyone had advice about it.

**Pull request merged**
